### ISSUE TITLE
Segfault on gem install libv8

### ISSUE THREAD

**Issue by ghost** [JoeNyland/docker-ruby-alpine-libv8#1]
I am using the base image 2.4.3-alpine3.7, and I'm getting a Segmentation fault on running 
`gem install libv8 -v 3.16.14.16`
It works perfectly on ruby:2.3.1-alpine-3.4

Do you have any idea why this is happening?

**Comment by JoeNyland** [comment]
I assume that you're referring to the official ruby images here as `2.4.3-alpine3.7` isn't an image I'm building here. Therefore, I'm not 100% sure why you're raising an issue on this repo...

I don't really follow Alpine Linux that much to suggest what could be causing `libv8` to build on Alpine 3.7, sorry. I can only suggest you raise an issue at https://github.com/cowboyd/libv8/issues and hopefully they might be able to help.
